- name: Install apache web server
  hosts: all
  become: True

  tasks:
  - name: update & upgrade server
    apt:
      upgrade: yes

  - name: install nginx
    apt:
      name: nginx
      state: latest

  # server setup bash
  - name: server setup
    script: server1nginxbash.sh
    args:
      chdir: /var/www/html